# Introduction To Pandas

- Pandas is a python library
- It is used for Data Clining , Transformation and Data Analysis
- It provides us 2 Data Structures
- Series -1 Minentional.i.e One Column
- Data Frame -2 Dimentional,i.e Table

#* Series

In [ ]:
import pandas as pd
s=pd.Series([2,4,7,9,10,1,3,5,6,34,67,78,34,23,36,27])
print(type(s))
print(s)

<class 'pandas.core.series.Series'>
0      2
1      4
2      7
3      9
4     10
5      1
6      3
7      5
8      6
9     34
10    67
11    78
12    34
13    23
14    36
15    27
dtype: int64

In [ ]:
s.head() # Display First 5 Rows

0     2
1     4
2     7
3     9
4    10
dtype: int64

In [ ]:
s.tail() # Display Last 5 Rows

0     2
1     4
2     7
3     9
4    10
dtype: int64

In [ ]:
s.info # Display Information

<bound method Series.info of 0      2
1      4
2      7
3      9
4     10
5      1
6      3
7      5
8      6
9     34
10    67
11    78
12    34
13    23
14    36
15    27
dtype: int64>

In [ ]:
s.describe()

count    16.000000
mean     21.625000
std      23.491488
min       1.000000
25%       4.750000
50%       9.500000
75%      34.000000
max      78.000000
dtype: float64

In [ ]:
df=pd.DataFrame({
    "Roll No":[2,4,7,9,4,21,3,5,6,34],
    "Name":["Avi","Rahul","Ram","Sham","Rahul","Yash","Sakshi","Pooja","Raja","Abhi"],
    "Class":["A","B","C","D","B","F","G","H","None","J"],
    "Age":[21,22,None,24,24,25,21,27,28,29],
    "Marks":[80,60,None,64,62,52,None,42,67,52]
})
print(type(df))
print(df)

<class 'pandas.core.frame.DataFrame'>
   Roll No    Name Class   Age  Marks
0        2     Avi     A  21.0   80.0
1        4   Rahul     B  22.0   60.0
2        7     Ram     C   NaN    NaN
3        9    Sham     D  24.0   64.0
4        4   Rahul     B  24.0   62.0
5       21    Yash     F  25.0   52.0
6        3  Sakshi     G  21.0    NaN
7        5   Pooja     H  27.0   42.0
8        6    Raja  None  28.0   67.0
9       34    Abhi     J  29.0   52.0

In [ ]:
df.isnull().sum()

Roll No    0
Name       0
Class      0
Age        1
Marks      2
dtype: int64

In [ ]:
df.tail()

   Roll No    Name Class   Age  Marks
5       21    Yash     F  25.0   52.0
6        3  Sakshi     G  21.0    NaN
7        5   Pooja     H  27.0   42.0
8        6    Raja  None  28.0   67.0
9       34    Abhi     J  29.0   52.0

In [ ]:
df.describe(include = object)

         Name Class
count      10    10
unique      9     9
top     Rahul     B
freq        2     2

In [ ]:
df.shape

(10, 5)

In [ ]:
df.sample(2)

   Roll No   Name Class   Age  Marks
0        2    Avi     A  21.0   80.0
7        5  Pooja     H  27.0   42.0

In [ ]:
df.Name

0       Avi
1     Rahul
2       Ram
3      Sham
4     Rahul
5      Yash
6    Sakshi
7     Pooja
8      Raja
9      Abhi
Name: Name, dtype: object

In [ ]:
df.rename(columns={"Name":"Student Name"},inplace=True)

In [ ]:
df

   Roll No Student Name Class   Age  Marks
0        2          Avi     A  21.0   80.0
1        4        Rahul     B  22.0   60.0
2        7          Ram     C   NaN    NaN
3        9         Sham     D  24.0   64.0
4        4        Rahul     B  24.0   62.0
5       21         Yash     F  25.0   52.0
6        3       Sakshi     G  21.0    NaN
7        5        Pooja     H  27.0   42.0
8        6         Raja  None  28.0   67.0
9       34         Abhi     J  29.0   52.0

In [ ]:
df["Student Name"]

0       Avi
1     Rahul
2       Ram
3      Sham
4     Rahul
5      Yash
6    Sakshi
7     Pooja
8      Raja
9      Abhi
Name: Student Name, dtype: object

In [ ]:
df[["Student Name","Marks"]]

  Student Name  Marks
0          Avi   80.0
1        Rahul   60.0
2          Ram    NaN
3         Sham   64.0
4        Rahul   62.0
5         Yash   52.0
6       Sakshi    NaN
7        Pooja   42.0
8         Raja   67.0
9         Abhi   52.0

In [ ]:
df[df["Marks"]>78]

   Roll No Student Name Class   Age  Marks
0        2          Avi     A  21.0   80.0

In [ ]:
# Example: Change Avi's marks to 85
df.loc[df['Student Name'] == 'Avi', 'Marks'] = 85

# Display the updated DataFrame to verify
display(df)

   Roll No Student Name Class   Age  Marks
0        2          Avi     A  21.0   85.0
1        4        Rahul     B  22.0   60.0
2        7          Ram     C   NaN    NaN
3        9         Sham     D  24.0   64.0
4        4        Rahul     B  24.0   62.0
5       21         Yash     F  25.0   52.0
6        3       Sakshi     G  21.0    NaN
7        5        Pooja     H  27.0   42.0
8        6         Raja  None  28.0   67.0
9       34         Abhi     J  29.0   52.0